server:
  port: 8080
  servlet:
    context-path: /

logging:
  config: classpath:log/logback.xml
  path: C:\Users\a6924.GOLDDRAGON.COM\Desktop\log

spring:
  datasource:
    druid:
      loginUsername: root
      loginPassword: chenqinglin
      db1:
        username: root
        password: chenqinglin
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://icql.work:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        username: root
        password: chenqinglin
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://icql.work:3306/test2?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
        initialSize: 5
        minIdle: 5
        maxActive: 20
  redis:
    database: 0
    host: icql.work
    port: 6379
    password: chenqinglin
    jedis:
      pool:
        max-active: 8
        max-idle: 10
        min-idle: 0
        timeout: 1000
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=7200s

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: work.icql.springboot.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 4
    logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
