server:
  port: 8080
  servlet:
    context-path: /

logging:
  config: classpath:log/logback.xml
  path: log/

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
# 开启处理 404异常，但swagger会失效
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
  datasource:
    druid:
      loginUsername: root
      loginPassword: chenqinglin
      db1:
        username: root
        password: chenqinglin
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://icql.work:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        username: root
        password: chenqinglin
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://icql.work:3306/test2?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
        initialSize: 5
        minIdle: 5
        maxActive: 20
  redis:
    database: 0
    host: icql.work
    port: 6379
    password: chenqinglin
    jedis:
      pool:
        max-active: 8
        max-idle: 10
        min-idle: 0
        timeout: 1000
  rabbitmq:
    host: icql.work
    port: 5672
    username: root
    password: chenqinglin
#    listener:
#      direct:
#        acknowledge-mode: manual #消费者ack 手动确认
#      simple:
#        acknowledge-mode: manual #消费者ack 手动确认
  cache:
    type: redis
    redis-default-expire: 600
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=7200s

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml

websocket:
  socket-path: /websocket/endpoint
  broadcast-path: /websocket/broadcast
  point-path: /websocket/point